# /docker-compose.yml
version: '3.9'

services:
  rescue-api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${RESCUE_API_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${RESCUE_API_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${RESCUE_API_POSTGRES_DB:-rescuedb}
      PGUSER: ${RESCUE_API_POSTGRES_USER:-user}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
