"""Add rescues table

Revision ID: 0d791ade9e9c
Revises: 50454163449e
Create Date: 2025-08-21 09:13:58.141291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d791ade9e9c'
down_revision: Union[str, Sequence[str], None] = '50454163449e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescues',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=True),
        sa.Column('rescuer_id', sa.Integer(), nullable=True),
        sa.Column('magnet_link', sa.Text(), nullable=False),
        sa.Column('status', sa.Enum('success', 'fail', name='status'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
        sa.ForeignKeyConstraint(['rescuer_id'], ['rescuers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('asset_id', 'rescuer_id')
    )
    op.create_unique_constraint("uq_rescuer_name", 'rescuers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_rescuer_name", 'rescuers', type_='unique')
    op.drop_table('rescues')
    # ### end Alembic commands ###
