"""AssetKind : added name.

Revision ID: 12a15d98af95
Revises: 37a3ded45c86
Create Date: 2025-07-03 17:55:32.312405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a15d98af95'
down_revision: Union[str, Sequence[str], None] = '37a3ded45c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_kinds', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'asset_kinds', ['name'])
    op.add_column('assets', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('mtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'mtime')
    op.drop_column('assets', 'size')
    op.drop_constraint(None, 'asset_kinds', type_='unique')
    op.drop_column('asset_kinds', 'name')
    # ### end Alembic commands ###
