"""Change assets and resources relationship to many-to-many

Revision ID: 222627c18471
Revises: 8e808b40192d
Create Date: 2025-07-30 07:55:40.926658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '222627c18471'
down_revision: Union[str, Sequence[str], None] = '8e808b40192d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'asset_resource',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=True),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
        sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('asset_id', 'resource_id')
    )
    op.create_index(op.f('ix_assets_url'), 'assets', ['url'], unique=True)
    op.drop_constraint(op.f('assets_resource_id_fkey'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('assets_resource_id_fkey'), 'assets', 'resources', ['resource_id'], ['id'])
    op.drop_index(op.f('ix_assets_url'), table_name='assets')
    op.drop_table('asset_resource')
    # ### end Alembic commands ###
