"""init

Revision ID: 2f9f22e8382c
Revises:
Create Date: 2025-06-19 10:54:03.418644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f9f22e8382c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "asset_kinds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dg_id", sa.String(), nullable=False),
        sa.Column("dg_name", sa.String(), nullable=False),
        sa.Column("dg_title", sa.String(), nullable=False),
        sa.Column("dg_created", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dg_id", sa.String(), nullable=False),
        sa.Column("dg_organization_id", sa.String(), nullable=False),
        sa.Column("dg_name", sa.String(), nullable=False),
        sa.Column("dg_title", sa.String(), nullable=False),
        sa.Column("dg_notes", sa.String(), nullable=False),
        sa.Column("dg_metadata_created", sa.DateTime(), nullable=False),
        sa.Column("dg_metadata_modified", sa.DateTime(), nullable=False),
        sa.Column("access_direct_dl_count", sa.Integer(), nullable=False),
        sa.Column("access_total_count", sa.Integer(), nullable=False),
        sa.Column("dg_created", sa.DateTime(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dg_id", sa.String(), nullable=False),
        sa.Column("dg_name", sa.String(), nullable=False),
        sa.Column("dg_description", sa.String(), nullable=False),
        sa.Column("dg_resource_locator_function", sa.String(), nullable=False),
        sa.Column("dg_resource_locator_protocol", sa.String(), nullable=False),
        sa.Column("dg_mimetype", sa.String(), nullable=False),
        sa.Column("dg_state", sa.String(), nullable=False),
        sa.Column("dg_created", sa.DateTime(), nullable=False),
        sa.Column("dg_metadata_modified", sa.DateTime(), nullable=False),
        sa.Column("dg_url", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("kind_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kind_id"],
            ["asset_kinds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assets")
    op.drop_table("resources")
    op.drop_table("datasets")
    op.drop_table("organizations")
    op.drop_table("asset_kinds")
    # ### end Alembic commands ###
