"""Fix foreign keys nullabilty

Revision ID: 4670cd8f1d65
Revises: 0d791ade9e9c
Create Date: 2025-08-21 09:36:29.986652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4670cd8f1d65'
down_revision: Union[str, Sequence[str], None] = '0d791ade9e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'asset_resource',
        'asset_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'asset_resource',
        'resource_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'rescues',
        'asset_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.alter_column(
        'rescues',
        'rescuer_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'rescues',
        'rescuer_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'rescues',
        'asset_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'asset_resource',
        'resource_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'asset_resource',
        'asset_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    # ### end Alembic commands ###
