"""Set rescue table as class

Revision ID: 8e7749efc63b
Revises: 4670cd8f1d65
Create Date: 2025-08-25 13:29:29.446003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e7749efc63b'
down_revision: Union[str, Sequence[str], None] = '4670cd8f1d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'rescues',
        'id',
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True
    )
    op.alter_column(
        'rescues',
        'magnet_link',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False
    )
    op.alter_column(
        'rescues',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column(
        'rescues',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'rescues',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column(
        'rescues',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('CURRENT_TIMESTAMP')
    )
    op.alter_column(
        'rescues',
        'magnet_link',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False
    )
    op.alter_column(
        'rescues',
        'id',
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True
    )
    # ### end Alembic commands ###
