"""Add index to asset_resource

Revision ID: dd4bfdee96c5
Revises: f2cef33e6118
Create Date: 2025-09-20 19:13:45.347135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd4bfdee96c5'
down_revision: Union[str, Sequence[str], None] = 'f2cef33e6118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('asset_resource_asset_id_resource_id_idx', 'asset_resource', ['asset_id', 'resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('asset_resource_asset_id_resource_id_idx', table_name='asset_resource')
    # ### end Alembic commands ###
